### ISSUE TITLE
No body even when included

### ISSUE THREAD

**Issue by davesgonechina** [sanzoghenzo/markdownr#49]
Seems to have started with v1.5.0? On Android 13 and didn't see this until past week or so - `Include Body` already enabled but body isn't all there. Websites this previously worked on no longer do.

![Screenshot_20231008-132534](https://github.com/sanzoghenzo/markdownr/assets/3881072/9ae233f1-8da1-4f07-8734-61e8b974954e)
![Screenshot_20231008-132544](https://github.com/sanzoghenzo/markdownr/assets/3881072/28c0c776-66a1-4c5e-a1d4-a9088360827b)

**Comment by davesgonechina** [comment]
Confirmed, downgraded to 1.4.1 and now body is included
![Screenshot_20231008-133517](https://github.com/sanzoghenzo/markdownr/assets/3881072/46d924fc-75e6-4f1b-a153-650428ad76b1)

**Comment by sanzoghenzo** [comment]
Hi @davesgonechina, thanks for the report; 
The issue was already reported in #47 and should be fixed in 1.5.1.
It takes a while for f-droid to detect the tag and build the release, so please hang on 😉 
The workaround for version 1.5.0 is to disable and then re-enable the option, then it should be fully functional!

**Comment by davesgonechina** [comment]
@sanzoghenzo fwiw I tried disabling and re-enabling a few times before downgrading and it didn't work.

**Comment by sanzoghenzo** [comment]
That's strange... Anyway, version 1.5.1 is finally available on F-Droid!
Let me know if you still have problems
